apiVersion: v1
kind: Pod
metadata:
  name: first-pod
  labels:
    app: first-pod
spec:
  containers:
    - name: myapp
      image: busybox
      command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 10']
  restartPolicy: Never
