
apiVersion: v1
kind: Pod
metadata:
  name: namespace-pod
  namespace: myapp-ns
  labels:
    app: first-pod
spec:
  containers:
    - name: myapp
      image: busybox
      command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 120']
