apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: webapp
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
  restartPolicy: Never
