apiVersion: v1
kind: Pod
metadata:
  name: my-command-pod
  labels:
    app: my-command-app
spec:
  containers:
    - name: command-container
      image: busybox
      command: ['echo']
      args: ['This is command agruments']
  restartPolicy: Never
