apiVersion: v1
kind: Pod
metadata:
  name: nginx-container-pod
  labels:
    app: nginxapp
spec:
  containers:
    - name: nginx-container
      image: nginx:alpine
      ports:
        - containerPort: 80
